using System.Reflection;

namespace ShellPOC.Helpers;

public static class FontHelper
{
    public static double TabsIconSize
    {
        get
        {
#if ANDROID
            return 20;
#endif
#if IOS
            return 25;
#endif
        }
    }

    public static List<(string name, string icon)> GetAllValues()
    {
        var returnVal = new List<(string name, string icon)>();

        var fieldInfo = typeof(FontHelper)
            .GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy)
            .Where(fi => fi.IsLiteral && !fi.IsInitOnly)
            .ToList();

        if(fieldInfo != null)
        {
            foreach (var info in fieldInfo)
            {
                if(info != null)
                {
                    var value = info.GetRawConstantValue();
                    if(value != null)
                    {
                        returnVal.Add((info.Name, (string)value));
                    }
                }
            }
        }

        return returnVal;
    }

    // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'

    public const string JuniperClose = "\ue90c";
    public const string JuniperLocation = "\ue91a";
    public const string JuniperSettings = "\ue92b";
    public const string JuniperQrCode1 = "\ue98b";
    public const string JuniperQrCode2 = "\ue9ef";
    public const string JuniperAprBuyWeek = "\ue9b4";
    public const string JuniperIconMap = "\ue9e5";
    public const string JuniperIconMore = "\ue9e6";
    public const string JuniperIconPlan = "\ue9e7";
    public const string JuniperIconSearchDir = "\ue9e8";
    public const string JuniperIconHome1 = "\ue9e9";
    public const string JuniperCircleCheck = "\ue9d6";
    public const string AndmoreMarkets = "\ue9f2";
    public const string FilterIcon = "\ue9be";
    public const string AddIcon = "\ue9c1";
    public const string LocationIcon = "\ue91a";
    public const string JuniperIconSupport = "\ue9fc";
    public const string JuniperIconEventsSearch = "\uea00";
    public const string JuniperIconHelp = "\ue9fe";
    public const string JuniperLogout = "\ue91c";
}
